### ISSUE TITLE
trimToWidth in 1.16-pre2

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#1427] opened 2020-06-05 14:10 UTC
`TextRenderer.trimToWidth` now returns a `class_5348` (`Text`'s superinterface) and `TextHandler.trimToWidth` returns a style. Previously both methods returned a text object and the renderer one was a wrapper. I think the style one in `TextHandler` should be renamed now.

**Comment by YanisBft** [comment] 2020-08-02 23:47
Duplicate of #1646

**Closed as completed by YanisBft** 2020-08-02 23:47 UTC
Labels: discussion
