### ISSUE TITLE
Stackoverflow error when exporting source.

### ISSUE THREAD

**Issue by SekoiaTree** [asiekierka/MinecraftPOMF#1434] opened 2020-06-06 17:17 UTC
https://pastebin.com/jyiaKNxG for the crash message
When you click file -> export source, enigma tries to export, but crashes shortly after.

Edit: this does not happen with export jar.

**Comment by liach** [comment] 2020-06-06 17:19
Duplicate of FabricMC/Enigma#202

**Closed as completed by liach** 2020-06-06 17:19 UTC
