### ISSUE TITLE
Package visibility issues

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [asiekierka/MinecraftPOMF#683] opened 2019-05-06 22:29 UTC
[Starting with 1.14 these were intended to be resolved](https://github.com/FabricMC/yarn/issues/615), but there are currently many issues.

A somewhat shortened report of classes that must be moved to the same packages:

```
ERROR: Must be in one package:
net/minecraft/world/loot/LootChoiceProvider
net/minecraft/world/loot/entry/AlternativeEntry
net/minecraft/world/loot/entry/AlternativeEntry$Builder
net/minecraft/world/loot/entry/CombinedEntry
net/minecraft/world/loot/entry/CombinedEntry$1
net/minecraft/world/loot/entry/CombinedEntry$Factory
net/minecraft/world/loot/entry/CombinedEntry$Serializer
net/minecraft/world/loot/entry/GroupEntry
net/minecraft/world/loot/entry/LootEntries
net/minecraft/world/loot/entry/LootEntries$Serializer
net/minecraft/world/loot/entry/LootEntry
net/minecraft/world/loot/entry/LootEntry$Builder
net/minecraft/world/loot/entry/LootEntry$Serializer
net/minecraft/world/loot/entry/SequenceEntry
ERROR: Must be in one package:
net/minecraft/client/gui/Screen
net/minecraft/client/gui/ingame/ChatScreen
net/minecraft/client/gui/ingame/ChatScreen$1
net/minecraft/client/gui/ingame/ChatScreen$SuggestionWindow
net/minecraft/client/gui/menu/CustomizeBuffetLevelScreen
net/minecraft/client/gui/menu/CustomizeBuffetLevelScreen$1
net/minecraft/client/gui/menu/CustomizeBuffetLevelScreen$BuffetBiomesListWidget
net/minecraft/client/gui/menu/CustomizeBuffetLevelScreen$BuffetBiomesListWidget$BuffetBiomeItem
net/minecraft/client/gui/menu/CustomizeFlatLevelScreen
net/minecraft/client/gui/menu/CustomizeFlatLevelScreen$1
net/minecraft/client/gui/menu/CustomizeFlatLevelScreen$SuperflatLayersListWidget
net/minecraft/client/gui/menu/CustomizeFlatLevelScreen$SuperflatLayersListWidget$SuperflatLayerItem
net/minecraft/client/gui/menu/NewLevelPresetsScreen
net/minecraft/client/gui/menu/NewLevelPresetsScreen$SuperflatPreset
net/minecraft/client/gui/menu/NewLevelPresetsScreen$SuperflatPresetsListWidget
net/minecraft/client/gui/menu/NewLevelPresetsScreen$SuperflatPresetsListWidget$SuperflatPresetItem
net/minecraft/client/gui/menu/ServerConnectingScreen
net/minecraft/client/gui/menu/ServerConnectingScreen$1
net/minecraft/client/gui/menu/options/LanguageOptionsScreen
net/minecraft/client/gui/menu/options/LanguageOptionsScreen$LanguageSelectionListWidget
net/minecraft/client/gui/menu/options/LanguageOptionsScreen$LanguageSelectionListWidget$LanguageItem
ERROR: Must be in one package:
net/minecraft/client/gui/MapRenderer
net/minecraft/client/gui/MapRenderer$1
net/minecraft/client/gui/MapRenderer$MapTexture
net/minecraft/client/network/ClientPlayNetworkHandler
net/minecraft/client/network/ClientPlayNetworkHandler$1
net/minecraft/client/network/PlayerListEntry
net/minecraft/client/network/PlayerListEntry$1
ERROR: Must be in one package:
net/minecraft/client/gui/ContainerScreen
net/minecraft/client/gui/container/VillagerScreen
net/minecraft/client/gui/container/VillagerScreen$WidgetButtonPage
ERROR: Must be in one package:
net/minecraft/recipe/CuttingRecipe
net/minecraft/recipe/CuttingRecipe$Serializer
net/minecraft/recipe/CuttingRecipe$Serializer$a
net/minecraft/recipe/RecipeSerializer
net/minecraft/recipe/cooking/CookingRecipe
net/minecraft/recipe/cooking/CookingRecipeSerializer
net/minecraft/recipe/cooking/CookingRecipeSerializer$RecipeFactory
```

The goal is to disable the [package access hack that fabric-loader uses to work around these issues](https://github.com/FabricMC/fabric-loader/blob/120493c6384e506f51fe48702ada176486148982/src/main/java/net/fabricmc/loader/launch/common/MappingConfiguration.java). This does not affect mods at the moment because the package access hack has remained active, but it does prevent loading minecraft classes with a regular class loader.

**Comment by JamiesWhiteShirt** [comment] 2019-05-06 22:49
This closely relates to #649 and we might be able to use it to select some solutions. It appears things should be generally flatter. For instance:

- `net/minecraft/client/gui/widget` and `net/minecraft/client/gui/menu` should be flattened into `net/minecraft/client/gui`
- subpackages of `net/minecraft/recipe` should be flattened (and moved to `net/minecraft/world/item/crafting` according to the analysis)

**Comment by NeunEinser** [comment] 2019-05-07 07:23
Hmm, most of these seem to be not in the same packages according to #649, though. And I doubt that all `gui` packages are one. There even seem to be missing obf. names between most assumed packages, suggesting a `package-info.java`

**Comment by NeunEinser** [comment] 2019-05-07 07:25
Hmm, most of these seem to be not in the same packages according to #649, though. And I doubt that all `gui` packages are one. There even seem to be missing obf. names between most assumed packages, suggesting a `package-info.java`
How up-to-date is #649 actually @Runemoro?

**Comment by Runemoro** [comment] 2019-05-07 11:24
> There even seem to be missing obf. names between most assumed packages, suggesting a package-info.java

Gaps in the list can also be caused by unused classes. Proguard removes all unused classes after they've been given a name, not just package-info. What do you mean by "how up-to-date"? It's the 1.14 classes.

**Comment by NeunEinser** [comment] 2019-05-07 11:37
>Gaps in the list can also be caused by unused classes

Well, yes, but classes missing at the end of an assumed package all the time seems like a big coincidence.

> What do you mean by "how up-to-date"? It's the 1.14 classes.

Well, if  `EntryListWidget` and `LevelListWidget` are in the same package, that indicates, that at least all of `net.minecraft.client.gui` `net.minecraft.client.gui.???.toast`, `net.minecraft.client.gui.font`, `net.minecraft.client.gui.menu` and `net.minecraft.client.gui.screen` are in the same package, going by your list and that just seems wrong as that's 162 classes in one package.

The missing names just are perfectly aligned for the packages here, as well.

I also don't know how `SupplyingResourceReloadListener ` and `SoundManager` would work, as `SupplyingResourceReloadListener ` is line 639 and `SoundManager` is line 3405

**Comment by Runemoro** [comment] 2019-05-07 11:55
> I also don't know how SupplyingResourceReloadListener and SoundManager would work

They don't have to be in the same pacakge. The tool used to generate the list is broken.

**Comment by NeunEinser** [comment] 2019-05-07 11:58
What? You mean the list in this issue? Or why do they not need to be in the same package?
So are the classes mentioned ontop an issue now, or not? If they aren't I suggest to close this issue and move further discussion to #649.

**Comment by Runemoro** [comment] 2019-05-07 11:59
> What? You mean the list in this issue? Or why do they not need to be in the same package?

Yes, the list is the issue. There are no visibility errors in those two classes.

**Comment by JamiesWhiteShirt** [comment] 2019-05-07 12:03
I assumed that checkMappings gave accurate reports. If not, I can at least confirm that there are package visibility issues. I had this happen when not using fabric-loader's access hacks: `java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class net.minecraft.recipe.cooking.CookingRecipeSerializer$RecipeFactory from class net.minecraft.recipe.RecipeSerializer`

**Comment by Runemoro** [comment] 2019-05-07 12:04
Here's the output from `checkMappings`:

```
ERROR: Must be in one package: net/minecraft/resource/SupplyingResourceReloadListener and net/minecraft/client/sound/SoundManager (method readSounds)
```

`readSounds` is used by SoundManager.load, which *overrides* SupplyingResourceReloadListener.load, so there is no issue.

**Comment by JamiesWhiteShirt** [comment] 2019-05-11 22:48
I have been tinkering with the verifier and produced a more accurate report of classes that must be in the same package. The updated report is in the issue description. The report 100% accurate, but I cannot guarantee 100% recall right now.

```
client/network/ClientPlayNetworkHandler and client/gui/MapRenderer$MapTexture
recipe/RecipeSerializer and recipe/cooking/CookingRecipeSerializer$RecipeFactory
world/loot/entry/AlternativeEntry and world/loot/LootChoiceProvider
world/loot/entry/CombinedEntry and world/loot/LootChoiceProvider
world/loot/entry/GroupEntry and world/loot/LootChoiceProvider
world/loot/entry/LootEntry and world/loot/LootChoiceProvider
world/loot/entry/SequenceEntry and world/loot/LootChoiceProvider
```

While I am still working on the verification script, we can figure out how to deal with the ones we know about and fix them right now.

**Comment by JamiesWhiteShirt** [comment] 2019-05-15 10:53
Updated the issue description again, this time describing full partitions of classes that must exist in the same package that currently do not.

**Comment by modmuss50** [comment] 2019-05-16 20:50
Should now be fixed. Thanks for help in sorting this out.

**Closed as completed by modmuss50** 2019-05-16 20:50 UTC
