### ISSUE TITLE
Entity#dealDamage is misleading

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#2430] opened 2021-05-24 13:25 UTC
This method itself doesn't reduce the health of any entities. This method looks more like a callback for enchantment things (like applying slowness to arthropods when bane of arthropods enchantment is used).

**Comment by YanisBft** [comment] 2021-05-24 13:33
Duplicate of #1737

**Closed as completed by YanisBft** 2021-05-24 13:33 UTC
Labels: bug
